volumes:
  persistence: false

## disable monitoring stack
victoria-metrics-k8s-stack:
  enabled: false
  prometheusOperator:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false
  prometheus:
    enabled: false

# disabled AntiAffinity
affinity:
  anti_affinity: false

components:
  broker: true          
  proxy: true
  toolset: false        
  autorecovery: false
  pulsar_manager: false
  functions: false

zookeeper:
  replicaCount: 1
  podMonitor:
    enabled: false


bookkeeper:
  replicaCount: 1
  configData:
    dbStorage_writeCacheMaxSizeMb: "32"
    dbStorage_readAheadCacheMaxSizeMb: "32"
    dbStorage_rocksDB_writeBufferSizeMB: "8"
    dbStorage_rocksDB_blockCacheSize: "8388608"
  podMonitor:
    enabled: false

broker:
  replicaCount: 1
  configData:
    autoSkipNonRecoverableData: "true"
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
    managedLedgerDefaultRetentionTimeInMinutes: "10080"
  podMonitor:
    enabled: false

proxy:
  replicaCount: 1
  podMonitor:
    enabled: false

autorecovery:
  podMonitor:
    enabled: false

auth:
  authentication:
    enabled: false
  authorization:
    enabled: false